# примеры API-запросов

# получение объявлений
GET localhost:8000/api/advertisements/
Content-Type: application/json

###
# создание объявления
POST localhost:8000/api/advertisements/
Content-Type: application/json
Authorization: Token 55fd1d8f88bcdce11138cd6ebf50a1053bf16424

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH localhost:8000/api/advertisements/1/
Content-Type: application/json
Authorization: Token 55fd1d8f88bcdce11138cd6ebf50a1053bf16424

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET localhost:8000/api/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET localhost:8000/api/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

###
